export const enUSAdminExtraMessages: Record<string, string> = {
  个人账号: "Account",
  账号: "Account",
  账号设置: "Account settings",
  个人信息: "Profile",
  修改密码: "Change password",
  当前密码: "Current password",
  新密码: "New password",
  确认新密码: "Confirm password",
  密码强度: "Password strength",
  未输入: "Empty",
  偏弱: "Weak",
  一般: "Fair",
  较强: "Strong",
  强: "Strong",
  清空: "Clear",
  保存密码: "Save password",
  保存修改: "Save changes",
  查看头像大图: "Preview avatar",
  上传头像: "Upload avatar",
  复制用户名: "Copy username",
  头像预览: "Avatar preview",
  修改头像: "Change avatar",
  待裁剪头像: "Avatar to crop",
  请选择图片: "Select an image",
  请选择头像图片: "Select an avatar image",
  选择图片: "Select image",
  缩小: "Zoom out",
  放大: "Zoom in",
  头像缩放: "Avatar zoom",
  预览: "Preview",
  提交: "Submit",
  重置: "Reset",
  取消: "Cancel",
  昵称不能为空: "Nickname is required",
  "昵称不能超过 64 个字符": "Nickname cannot exceed 64 characters",
  邮箱格式不正确: "Invalid email address",
  "手机号不能超过 32 个字符": "Phone number cannot exceed 32 characters",
  "头像地址不能超过 255 个字符": "Avatar URL cannot exceed 255 characters",
  账号信息已保存: "Account information saved",
  账号信息保存失败: "Failed to save account information",
  头像已更新: "Avatar updated",
  头像上传失败: "Failed to upload avatar",
  "请选择 jpg、png、webp 或 gif 图片": "Select a jpg, png, webp, or gif image",
  "头像不能超过 5 MB": "Avatar must be 5 MB or smaller",
  暂无可复制的用户名: "No username to copy",
  用户名已复制: "Username copied",
  "复制失败，请稍后重试": "Copy failed. Try again later.",
  "维护当前账号的头像、昵称和联系信息。":
    "Manage the avatar, nickname, and contact information for this account.",
  "头像、昵称和联系方式保存后立即生效。":
    "Avatar, nickname, and contact information take effect after saving.",
  "当前资料有修改，保存后会同步到当前账号。":
    "Profile changes will be synced to the current account after saving.",
  "当前资料已和服务器保持同步。":
    "Profile information is already in sync with the server.",
  请输入当前密码: "Enter current password",
  "新密码至少需要 10 位": "New password must be at least 10 characters",
  "新密码不能超过 128 位": "New password cannot exceed 128 characters",
  请再次输入新密码: "Confirm the new password",
  两次输入的新密码不一致: "The new passwords do not match",
  新密码不能和当前密码相同:
    "The new password cannot be the same as the current password",
  登录密码已更新: "Password updated",
  密码修改失败: "Failed to change password",
  "修改后请使用新密码登录当前账号。":
    "Use the new password next time you sign in to this account.",
  "至少 10 位，建议包含大小写字母、数字或符号。":
    "Use at least 10 characters. Uppercase, lowercase, numbers, or symbols are recommended.",
  "保存后服务端会校验当前密码是否正确。":
    "The server will verify the current password when saving.",
  隐藏密码: "Hide password",
  显示密码: "Show password",
  "输入新密码后显示强度。":
    "Password strength appears after you enter a new password.",
  "建议至少 10 位，并加入大小写、数字或符号。":
    "Use at least 10 characters and add letter case, numbers, or symbols.",
  "可以继续增加长度或更多字符类型。":
    "Add more length or character types to improve it.",
  "强度不错，继续增加长度会更稳。":
    "Good strength. More length makes it safer.",
  "强度良好，请妥善保存新密码。": "Strong password. Keep it safe.",
  "选择图片后裁剪为方形头像，提交后才会上传。":
    "Crop the image into a square avatar. It uploads only after submission.",
  "拖动图片调整位置，使用缩放控制头像范围。":
    "Drag the image to adjust position and use zoom to control the avatar area.",
  头像图片加载失败: "Failed to load avatar image",
  当前浏览器不支持头像裁剪: "This browser does not support avatar cropping",
  头像裁剪失败: "Failed to crop avatar",
  "{title} 的头像": "{title}'s avatar",

  全部: "All",
  成功: "Success",
  失败: "Failed",
  系统: "System",
  详情: "Details",
  复制: "Copy",
  已复制: "Copied",
  "复制失败，请手动选择文本复制。":
    "Copy failed. Select the text manually to copy.",
  操作模块: "Module",
  业务类型: "Business type",
  请求方式: "Method",
  操作人员: "Operator",
  操作地址: "IP address",
  请求地址: "Request address",
  请求路径: "Request path",
  "耗时(ms)": "Duration(ms)",
  消耗时间: "Duration",
  毫秒: "ms",
  操作时间: "Operated at",
  操作方法: "Handler",
  登录账号: "Login account",
  登录地址: "Login address",
  浏览器: "Browser",
  操作系统: "Operating system",
  提示消息: "Message",
  登录时间: "Login time",
  操作日志详情: "Operation log details",
  登录日志详情: "Login log details",
  "查看本次后台操作的请求、参数和执行结果。":
    "View the request, parameters, and result of this backend operation.",
  "查看本次登录的账号、客户端和执行状态。":
    "View the account, client, and status for this sign-in.",
  概要: "Summary",
  请求参数: "Request parameters",
  返回参数: "Response parameters",
  异常信息: "Exception",
  "加载详情中...": "Loading details...",
  "详情加载失败，请关闭后重试。":
    "Failed to load details. Close this dialog and try again.",
  "归属地查询中...": "Looking up location...",
  归属地查询失败: "Location lookup failed",
  "(无数据)": "(No data)",
  "搜索账号、IP、浏览器、消息...": "Search account, IP, browser, message...",
  暂无登录日志: "No login logs",
  "系统还没有记录到任何登录访问。": "No sign-in access has been recorded yet.",
  登录日志状态筛选: "Login log status filter",
  "搜索模块、人员、路径、IP...": "Search module, operator, path, IP...",
  暂无操作日志: "No operation logs",
  "系统还没有记录到任何后台操作。":
    "No backend operations have been recorded yet.",
  操作日志状态筛选: "Operation log status filter",

  字典数据: "Dictionary data",
  字典列表: "Dictionary data",
  "{name} 字典列表": "{name} dictionary data",
  "搜索字典标签、键值...": "Search dictionary label or value...",
  暂无字典数据: "No dictionary data",
  "当前字典类型下还没有字典数据。":
    "There is no data under this dictionary type yet.",
  新增字典数据: "Create dictionary data",
  字典数据状态: "Dictionary data status",
  字典数据暂不支持拖拽排序: "Dictionary data does not support drag sorting yet",
  缺少字典类型: "Missing dictionary type",
  拖拽调整排序: "Drag to reorder",
  全部展开: "Expand all",
  全部收起: "Collapse all",
  收起节点: "Collapse node",
  展开节点: "Expand node",
  "展开/折叠": "Expand/collapse",
  "全选/全不选": "Select/deselect all",
  父子联动: "Link parent and child",
  "正在加载权限...": "Loading permissions...",
  暂无权限: "No permissions",
  收起权限节点: "Collapse permission node",
  展开权限节点: "Expand permission node",
  顶级菜单: "Top-level menu",
  "搜索权限...": "Search permissions...",
  没有匹配的权限: "No matching permissions",
  选择菜单图标: "Select menu icon",
  当前: "Current",
  搜索图标名称或标识: "Search icon name or key",
  没有匹配的图标: "No matching icons",
  换一个关键词或分类试试: "Try another keyword or category.",
  当前显示: "Showing",
  个: "items",
  共: "of",
  上一页: "Previous",
  下一页: "Next",
  "正在加载角色...": "Loading roles...",
  请选择角色: "Select roles",
  "角色加载失败，请稍后重试。": "Failed to load roles. Try again later.",
  常用: "Common",
  组织: "Organization",
  内容: "Content",
  工具: "Tools",
  主页: "Home",
  设置: "Settings",
  配置: "Configuration",
  系统配置: "System config",
  侧栏: "Sidebar",
  分层: "Layers",
  流程: "Workflow",
  标签: "Tag",
  安全: "Security",
  身份认证: "Authentication",
  登录: "Login",
  审核: "Audit",
  参数: "Parameters",
  系统文件: "System files",
  用户验证: "User verification",
  用户配置: "User config",
  职位: "Position",
  身份卡: "ID card",
  数据: "Data",
  数据服务: "Data service",
  文档: "Documents",
  日志文档: "Log documents",
  树列表: "Tree list",
  清单: "Checklist",
  数据表: "Data table",
  展开目录: "Expand directory",
  归档: "Archive",
  包: "Package",
  盒子: "Box",
  资源包: "Packages",
  服务器: "Server",
  活动: "Activity",
  仪表盘: "Dashboard",
  性能: "Performance",
  存储: "Storage",
  网络: "Network",
  日志: "Logs",
  历史: "History",
  计划任务: "Scheduled jobs",
  日历: "Calendar",
  全局: "Global",
  插件: "Plugins",
  检索: "Search",
  上传: "Upload",
  下载: "Download",
  支付: "Payment",
  统计: "Statistics",
  柱状图: "Bar chart",
  报表: "Reports",

  节点管理: "Node management",
  节点: "Node",
  "节点 ID": "Node ID",
  节点名称: "Node name",
  域名: "Domain",
  域名与接入点: "Domain and endpoint",
  连接与流负载: "Connections and stream load",
  心跳与有效期: "Heartbeat and expiry",
  连接: "Connections",
  流: "Streams",
  负载未上报: "Load not reported",
  替换相同节点的未完成登记:
    "Replace an unfinished enrollment for the same node",
  "仅用于安装命令遗失或登记卡住；替换后，之前生成的命令会立即失效。":
    "Use only when the install command was lost or enrollment is stuck. The previous command stops working immediately.",
  最近心跳: "Last heartbeat",
  登记有效期至: "Enrollment expires",
  暂无: "N/A",
  全部状态: "All statuses",
  待接入: "Pending enrollment",
  安装中: "Installing",
  已过期: "Expired",
  初始化: "Initializing",
  降级: "Degraded",
  排空中: "Draining",
  异常: "Unhealthy",
  已禁用: "Disabled",
  节点状态筛选: "Node status filter",
  节点操作: "Node actions",
  接入命令: "Enrollment command",
  接入节点: "Enroll node",
  修改节点: "Edit node",
  删除节点: "Delete node",
  取消登记: "Cancel enrollment",
  取消节点登记: "Cancel node enrollment",
  排空连接: "Drain connections",
  恢复接入: "Resume traffic",
  启用节点: "Enable node",
  禁用节点: "Disable node",
  节点登记已取消: "Node enrollment cancelled",
  节点信息已更新: "Node details updated",
  节点已删除: "Node deleted",
  节点状态已更新: "Node status updated",
  节点列表已刷新: "Node list refreshed",
  "已获取服务器最新的节点状态。":
    "Fetched the latest node status from the server.",
  "当前账号没有节点列表权限。":
    "This account does not have permission to view the node list.",
  暂无节点: "No nodes",
  "当前还没有已接入或待接入的出口节点。":
    "There are no active or pending egress nodes yet.",
  新增节点: "Add node",
  节点信息未填写完整: "Node information is incomplete",
  "请检查表单中的必填项或格式提示。":
    "Check the required fields and format hints in the form.",
  "请输入节点 ID": "Enter a node ID",
  "节点 ID 不能超过 128 个字符": "Node ID cannot exceed 128 characters",
  "节点 ID 仅支持字母、数字、下划线和连字符":
    "Node ID can contain only letters, numbers, underscores, and hyphens",
  请输入域名: "Enter a domain",
  "请输入有效的完整域名，不要包含协议或端口":
    "Enter a valid fully qualified domain without a protocol or port",
  请输入节点名称: "Enter a node name",
  "节点名称不能超过 128 个字符": "Node name cannot exceed 128 characters",
  最大连接数必须是整数: "Maximum connections must be an integer",
  "最大连接数不能小于 1": "Maximum connections cannot be less than 1",
  "最大连接数不能超过 16384": "Maximum connections cannot exceed 16384",
  最大流数必须是整数: "Maximum streams must be an integer",
  "最大流数不能小于 1": "Maximum streams cannot be less than 1",
  "最大流数不能超过 65535": "Maximum streams cannot exceed 65535",
  安装命令已复制: "Install command copied",
  普通安装命令已复制: "Native install command copied",
  普通安装脚本已复制: "Native install script copied",
  "Docker 安装命令已复制": "Docker install command copied",
  "Docker 安装脚本已复制": "Docker install script copied",
  卸载命令已复制: "Uninstall command copied",
  卸载脚本已复制: "Uninstall script copied",
  "复制失败，请手动选择命令复制。":
    "Copy failed. Select the command manually to copy it.",
  安装命令已生成: "Install command generated",
  接入命令已生成: "Enrollment command generated",
  一键脚本已生成: "One-click scripts generated",
  节点已创建: "Node created",
  "请在目标服务器上执行以下一次性命令。":
    "Run the following one-time command on the target server.",
  "选择一种安装方式，在目标服务器执行对应的一键脚本。":
    "Choose an installation method and run its one-click script on the target server.",
  "选择一种方式，在目标服务器执行一键安装脚本。":
    "Choose a method and run the one-click installer on the target server.",
  该命令仅在本次弹窗中显示: "This command is shown only in this dialog",
  这些脚本仅在本次弹窗中显示: "These scripts are shown only in this dialog",
  "命令包含一次性登记令牌，请勿转发或在共享终端执行。执行完成后，请清理包含该命令的 shell 历史；关闭弹窗后将无法再次查看。":
    "The command contains a one-time enrollment token. Do not share it or run it in a shared terminal. After installation, remove the command from shell history; it cannot be viewed again after closing this dialog.",
  "安装脚本包含一次性登记令牌，请勿转发或在共享终端执行。普通安装和 Docker 安装只需选择一种；关闭弹窗后将无法再次查看。":
    "The installer contains a one-time enrollment token. Do not share it or run it in a shared terminal. Choose either native or Docker installation; the scripts cannot be viewed again after closing this dialog.",
  有效期至: "Expires at",
  安装命令: "Install command",
  复制命令: "Copy command",
  "普通安装（systemd）": "Native install (systemd)",
  普通安装: "Native install",
  "Docker 安装": "Docker install",
  安装方式: "Installation method",
  安装与维护方式: "Install and maintenance method",
  普通安装一键脚本: "Native one-click install script",
  "Docker 一键安装脚本": "Docker one-click install script",
  一键卸载脚本: "One-click uninstall script",
  复制一键脚本: "Copy one-click script",
  复制脚本: "Copy script",
  "先在节点服务器执行卸载，再删除平台中的节点记录。":
    "Run the uninstaller on the node server before deleting its platform record.",
  "正在获取卸载脚本...": "Loading uninstall script...",
  "卸载脚本获取失败，仍可继续删除节点记录。":
    "Failed to load the uninstall script. You can still delete the node record.",
  卸载: "Uninstall",
  复制普通安装命令: "Copy native install command",
  "复制 Docker 安装命令": "Copy Docker install command",
  复制卸载命令: "Copy uninstall command",
  "直接安装 amd64/arm64 原生程序并注册 systemd 服务。":
    "Install the amd64/arm64 native binary and register a systemd service.",
  "自动识别 amd64/arm64，安装原生程序并注册 systemd 服务。":
    "Detect amd64/arm64 automatically, install the native binary, and register a systemd service.",
  "安装或复用 Docker，通过 Compose 运行 amd64/arm64 镜像。":
    "Install or reuse Docker and run the amd64/arm64 image with Compose.",
  "自动识别 amd64/arm64，安装或复用 Docker 并启动 Egress 容器。":
    "Detect amd64/arm64 automatically, install or reuse Docker, and start the Egress container.",
  "自动识别普通安装或 Docker 安装；保留 Docker 和 Certbot 证书，节点记录需在列表中另行删除。":
    "Automatically detect native or Docker mode and preserve Docker and Certbot certificates. Delete the node record separately from the list.",
  "自动识别普通安装或 Docker 安装并清理 Egress；节点记录仍需在列表中删除。":
    "Detect native or Docker installation automatically and remove Egress. Delete the node record separately from the list.",
  "安装脚本默认使用最新版本；需要固定版本时可向 install.sh 传入 --version <版本号>。脚本连接成功后，节点会自动转为在线状态。":
    "The installer uses the latest version by default. Pass --version <version> to install.sh to pin one. The node becomes online automatically after the script connects.",
  "普通安装和 Docker 安装默认使用最新版本，并自动适配 amd64/arm64；需要固定版本时，可向 install.sh 传入 --version <版本号>。连接成功后，节点会自动转为在线状态。":
    "Native and Docker installation use the latest version by default and detect amd64/arm64 automatically. Pass --version <version> to install.sh to pin one. The node becomes online automatically after it connects.",
  "脚本包含一次性登记令牌，仅在本次弹窗显示；普通安装和 Docker 只需选择一种。":
    "The script contains a one-time enrollment token and is only shown in this dialog. Choose either native or Docker installation.",
  "脚本执行并连接成功后，节点会自动转为在线状态。":
    "The node becomes online automatically after the script connects successfully.",
  当前状态: "Current status",
  "TLS 已启用": "TLS enabled",
  无需证书: "No certificate required",
  完成: "Done",
  "创建一次性登记命令，再到目标服务器完成安装。":
    "Generate a one-time enrollment command, then finish installation on the target server.",
  "填写节点信息，系统将自动生成节点 ID 和一次性安装命令。":
    "Enter the node details. The system will generate the node ID and one-time install command.",
  "修改节点名称；域名和运行容量由已安装节点配置保持。":
    "Edit the node name. The installed node keeps its domain and runtime capacity configuration.",
  "修改待接入节点后会生成新的安装命令，旧命令立即失效。":
    "Editing a pending node generates a new install command and invalidates the previous command immediately.",
  "重新生成一次性接入命令，并在目标服务器选择一种方式完成安装。":
    "Generate a new one-time enrollment command, then choose an installation method on the target server.",
  将生成新的接入命令: "A new enrollment command will be generated",
  "生成后，之前生成的命令会立即失效；请复制新命令到目标服务器执行。":
    "The previous command becomes invalid immediately after generation. Copy the new command and run it on the target server.",
  "如目标机器已有残留安装，请先执行卸载脚本；删除后当前一次性安装命令立即失效。":
    "If the target machine has a partial installation, run the uninstaller first. Deleting the node immediately invalidates its one-time installer.",
  "请先执行卸载脚本清理节点服务；在线节点仅在完全未占用时可删除，离线节点会自动解除环境绑定，但存在活动运行时仍会阻止删除。":
    "Run the uninstaller first. Online nodes can be deleted only when completely unused. Offline nodes release their environment assignments automatically, but active runtimes still block deletion.",
  已接入节点的域名保持不变: "The domain of a connected node remains unchanged",
  "域名关联当前 Egress 接入点；如需更换域名，请新增节点并完成迁移后再删除旧节点。":
    "The domain is bound to the current Egress endpoint. To change it, add and migrate to a new node before deleting the old one.",
  "数据通道 TLS": "Data-plane TLS",
  测试环境: "Development",
  正式环境: "Production",
  "未启用，无需证书": "Disabled; no certificate required",
  "正在确认 Server 环境": "Checking Server environment",
  "环境确认完成后才可以生成安装命令。":
    "The install command can be generated after the environment check completes.",
  "无法确认 Server 环境": "Unable to determine Server environment",
  "请检查 Server 的 Egress 安装配置后重试。":
    "Check the Server Egress installation configuration and try again.",
  测试环境接入: "Development enrollment",
  正式环境接入: "Production enrollment",
  "Server 当前为测试环境，安装命令使用 HTTP 数据通道，不需要域名证书。":
    "The Server is in development mode. The install command uses an HTTP data plane and does not require a domain certificate.",
  "Server 当前为正式环境，节点域名必须解析到公网 IPv4，并准备有效 TLS 证书。":
    "The Server is in production mode. The node domain must resolve to a public IPv4 address and have a valid TLS certificate.",
  节点地址: "Node address",
  节点域名: "Node domain",
  替换相同域名的未完成登记:
    "Replace an unfinished enrollment for the same domain",
  "搜索节点名称、ID、地址...": "Search node name, ID, or address...",
  "只填写域名，不要包含 http://、https:// 或端口。":
    "Enter only the domain without http://, https://, or a port.",
  高级容量配置: "Advanced capacity",
  最大连接数: "Maximum connections",
  最大流数: "Maximum streams",
  在线: "Online",
  离线: "Offline",
  正在连接实时状态: "Connecting live status",
  节点状态实时更新: "Node status is live",
  "实时状态已断开，正在重连": "Live status disconnected. Reconnecting",
  实时状态已关闭: "Live status closed",
  正在生成命令: "Generating command",
  正在保存节点: "Saving node",
  生成安装命令: "Generate install command",
  生成并显示接入命令: "Generate and show enrollment command",
  保存并重新生成命令: "Save and regenerate command",
  "取消后当前一次性安装命令将立即失效。":
    "The current one-time install command becomes invalid immediately.",
  "删除后当前一次性安装命令将立即失效。":
    "Deleting the pending node invalidates its one-time install command immediately.",
  "排空后节点不再接收新的环境分配；已分配环境和现有连接会继续使用。":
    "The node stops receiving new environment assignments; assigned environments and existing connections continue to use it.",
  "禁用后节点将停止接收新连接；有活动连接时后端会拒绝本次操作。":
    "The node stops accepting new connections. The backend rejects this action while connections are active.",
  "启用后节点可以重新接收连接，并退出排空状态。":
    "The node can accept connections again and leaves draining state.",
  "恢复后节点可以重新接收连接。":
    "The node can accept connections again after resuming.",
}
